apiVersion: v1
kind: Service
metadata:
  name: candy-neutrino-s
spec:
  ports:
  - name: peer
    port: 9735
    targetPort: 9735
  - name: rpc
    port: 10009
    targetPort: 10009
  - name: prometheus
    port: 8989
    targetPort: 8989
  selector:
    app: candy-neutrino
  type: LoadBalancer